---
- name: test an instance
  hosts: "*"
  become: yes
  tasks:

  - name: Upgrade/Update packages
    apt:
      upgrade: yes
      update_cache: yes 


  - name: Make dir
    command: "{{ item }}"
    loop:
      - mkdir /node
      - cd /node


  - name: "wget"
    become: yes 
    shell: "{{ item }}"
    args:
      chdir: /node
    loop:
            - useradd --no-create-home node_exporter \
            - wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz \
            - tar xzf node_exporter-1.0.1.linux-amd64.tar.gz \
            - cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter \
            - rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64
