---
- name: "Update Packages"
  become: yes
  apt:
      update_cache: yes 

- name: "wget"
  become: yes 
  command: "{{item}}"
  with_items:
        - useradd --no-create-home node_exporter \
        - wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz \
        - tar xzf node_exporter-1.0.1.linux-amd64.tar.gz \
        - cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter \
        - rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: "CreateSystemdUnit"
  become: yes 
  command:  |
             touch /etc/systemd/system/node-exporter.service \
              echo "[Unit]" >> /etc/systemd/system/node-exporter.service \
              echo "[Unit]" >> /etc/systemd/system/node-exporter.service \
              echo "Description=Prometheus Node Exporter Service" >> /etc/systemd/system/node-exporter.service \
              echo "After=network.target" >> /etc/systemd/system/node-exporter.service \
              echo "User=node_exporter" >> /etc/systemd/system/node-exporter.service \
              echo "Group=node_exporter" >> /etc/systemd/system/node-exporter.service \
              echo "Type=simple" >> /etc/systemd/system/node-exporter.service \
              echo "ExecStart=/usr/local/bin/node_exporter" >> /etc/systemd/system/node-exporter.service \
              echo "[Install]" >> /etc/systemd/system/node-exporter.service \
              echo "WantedBy=multi-user.target" >> /etc/systemd/system/node-exporter.service \

- name: "Enable"
  become: yes 
  command:  systemctl daemon-reload \
            systemctl enable --now node-exporter