
---  
  - name: Upgrade/Update packages  
    apt:
      upgrade: yes
      update_cache: yes 

  - name: Create a directory 
    file:
      path: /node
      state: directory

  - name: Create systemd unit
    shell: "{{ item }}"
    args:
      chdir: /etc/systemd/system/
    loop:
      - echo "[Unit]" 1> node-exporter.service
      - echo "Description=Prometheus Node Exporter Service" >> /etc/systemd/system/node-exporter.service
      - echo "After=network.target" >> /etc/systemd/system/node-exporter.service
      - echo "[Service]" >> /etc/systemd/system/node-exporter.service
      - echo "User=node_exporter" >> /etc/systemd/system/node-exporter.service
      - echo "Group=node_exporter" >> /etc/systemd/system/node-exporter.service
      - echo "Type=simple" >> /etc/systemd/system/node-exporter.service 
      - echo "ExecStart=/usr/local/bin/node_exporter" >> /etc/systemd/system/node-exporter.service 
      - echo "[Install]" >> /etc/systemd/system/node-exporter.service
      - echo "WantedBy=multi-user.target" >> /etc/systemd/system/node-exporter.service
    become: yes 

  - name: "wget"
    become: yes 
    shell: "{{ item }}"
    args:
      chdir: /node
    loop:
            - useradd --no-create-home node_exporter 
            - wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz 
            - tar xzf node_exporter-1.0.1.linux-amd64.tar.gz 
            - cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter 



  - name: create .service unit
    file:
      path: /etc/systemd/system/node-exporter.service
      state: touch
    become: yes

